import Foundation
import Testing

@testable import DirnexCore

/// The lines below are **captured**, not composed: each was produced by the named tool on macOS 26
/// over a file called `plain.txt` holding `hello checksum world\n`, and pasted in verbatim. A
/// fixture written from memory of a format is the one thing that cannot prove interop.
@Suite("ChecksumManifest")
struct ChecksumManifestTests {
    private static let helloSHA256 =
        "54b546dd1abc7108f73affc828b0771155ac437c380a245f1f183ca4d455c5fc"
    private static let helloMD5 = "81f90f926b3e019b743181fd8cdff9bb"

    // MARK: - The six producers

    @Test("shasum / md5sum / sha256sum: <hex>␣␣<name>")
    func gnuText() throws {
        let manifest = try ChecksumManifest.parse("\(Self.helloSHA256)  plain.txt\n")
        #expect(manifest.algorithm == .sha256)
        #expect(manifest.entries.count == 1)
        #expect(manifest.entries.first?.name == "plain.txt")
        #expect(manifest.entries.first?.digest == Self.helloSHA256)
        #expect(manifest.entries.first?.isBinary == false)
    }

    @Test("shasum -b: <hex>␣*<name>")
    func gnuBinary() throws {
        let manifest = try ChecksumManifest.parse("\(Self.helloSHA256) *plain.txt\n")
        #expect(manifest.entries.first?.name == "plain.txt")
        #expect(manifest.entries.first?.isBinary == true)
    }

    @Test("BSD md5: MD5 (<name>) = <hex>")
    func bsdLabelled() throws {
        let manifest = try ChecksumManifest.parse("MD5 (plain.txt) = \(Self.helloMD5)\n")
        #expect(manifest.algorithm == .md5)
        #expect(manifest.entries.first?.name == "plain.txt")
        #expect(manifest.entries.first?.digest == Self.helloMD5)
    }

    /// The form `shasum -c` refuses outright — reading it is the whole point of a tolerant parser.
    @Test("openssl dgst: SHA256(<name>)= <hex>")
    func opensslLabelled() throws {
        let manifest = try ChecksumManifest.parse("SHA256(plain.txt)= \(Self.helloSHA256)\n")
        #expect(manifest.algorithm == .sha256)
        #expect(manifest.entries.first?.name == "plain.txt")
        #expect(manifest.entries.first?.digest == Self.helloSHA256)
    }

    @Test("md5 -r: <hex>␣<name>")
    func bsdReversed() throws {
        let manifest = try ChecksumManifest.parse("\(Self.helloMD5) plain.txt\n")
        #expect(manifest.algorithm == .md5)
        #expect(manifest.entries.first?.name == "plain.txt")
        #expect(manifest.entries.first?.isBinary == false)
    }

    @Test("crc32: a bare digest takes the name the caller implies")
    func bareDigest() throws {
        let manifest = try ChecksumManifest.parse("4dbf2cc1\n", implicitName: "plain.txt")
        #expect(manifest.algorithm == .crc32)
        #expect(manifest.entries.first?.name == "plain.txt")
        #expect(manifest.entries.first?.digest == "4dbf2cc1")
    }

    @Test("crc32: a bare digest with nothing implied has no name")
    func bareDigestUnnamed() throws {
        let manifest = try ChecksumManifest.parse("4dbf2cc1")
        #expect(manifest.entries.first?.name.isEmpty == true)
    }

    @Test(".sfv: <name>␣<hex>, with ; comments")
    func sfv() throws {
        let text = """
        ; Generated by WIN-SFV32 v1.1
        ;
        plain.txt 4dbf2cc1
        name with spaces.txt 485e125e
        """
        let manifest = try ChecksumManifest.parse(text)
        #expect(manifest.algorithm == .crc32)
        #expect(manifest.entries.map(\.name) == ["plain.txt", "name with spaces.txt"])
        #expect(manifest.entries.map(\.digest) == ["4dbf2cc1", "485e125e"])
    }

    // MARK: - Awkward real cases

    @Test("names with spaces survive every form")
    func namesWithSpaces() throws {
        let spaced = "e404a071c8d352d4d5c8c2d3b25ffefe9a651bc22465042ffd0c2a65ab312c74"
        let gnu = try ChecksumManifest.parse("\(spaced)  name with spaces.txt")
        #expect(gnu.entries.first?.name == "name with spaces.txt")

        let bsd = try ChecksumManifest.parse("MD5 (name with spaces.txt) = \(Self.helloMD5)")
        #expect(bsd.entries.first?.name == "name with spaces.txt")

        let openssl = try ChecksumManifest.parse("SHA256(name with spaces.txt)= \(spaced)")
        #expect(openssl.entries.first?.name == "name with spaces.txt")
    }

    /// `shasum` marks an escaped line with a leading `\`; Apple's `/sbin/sha256sum` writes the same
    /// name raw. Both are real output from the same Mac, and both must yield `back\slash.txt`.
    @Test("shasum's leading-backslash escaping is undone; a raw backslash is left alone")
    func escapedNames() throws {
        let digest = "87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7"
        let escaped = try ChecksumManifest.parse("\\\(digest)  back\\\\slash.txt")
        #expect(escaped.entries.first?.name == "back\\slash.txt")

        let raw = try ChecksumManifest.parse("\(digest)  back\\slash.txt")
        #expect(raw.entries.first?.name == "back\\slash.txt")
    }

    @Test("an escaped newline in a name is decoded")
    func escapedNewline() throws {
        let digest = "0263829989b6fd954f72baaf2fc64bc2e2f01d692d4de72986ea808f6e99813f"
        let manifest = try ChecksumManifest.parse("\\\(digest)  new\\nline.txt")
        #expect(manifest.entries.first?.name == "new\nline.txt")
    }

    @Test("a UTF-8 BOM does not become part of the first digest")
    func utf8BOM() throws {
        var data = Data([0xEF, 0xBB, 0xBF])
        data.append(Data("\(Self.helloSHA256)  plain.txt\n".utf8))
        let manifest = try ChecksumManifest.parse(data)
        #expect(manifest.entries.first?.digest == Self.helloSHA256)
        #expect(manifest.entries.first?.name == "plain.txt")
    }

    @Test("a UTF-16 file is decoded from its BOM")
    func utf16BOM() throws {
        let text = "\(Self.helloSHA256)  Привет.txt\n"
        let data = try #require(text.data(using: .utf16))
        let manifest = try ChecksumManifest.parse(data)
        #expect(manifest.entries.first?.name == "Привет.txt")
    }

    @Test("CRLF and bare CR line endings both parse")
    func lineEndings() throws {
        let crlf = try ChecksumManifest.parse(
            "\(Self.helloSHA256)  a.txt\r\n\(Self.helloSHA256)  b.txt\r\n"
        )
        #expect(crlf.entries.map(\.name) == ["a.txt", "b.txt"])

        let cr = try ChecksumManifest.parse(
            "\(Self.helloSHA256)  a.txt\r\(Self.helloSHA256)  b.txt"
        )
        #expect(cr.entries.map(\.name) == ["a.txt", "b.txt"])
    }

    @Test("a missing trailing newline is fine")
    func noTrailingNewline() throws {
        let manifest = try ChecksumManifest.parse("\(Self.helloSHA256)  plain.txt")
        #expect(manifest.entries.count == 1)
    }

    @Test("blank lines and # comments are skipped without being reported")
    func commentsAndBlanks() throws {
        let text = """

        # written by hand

        \(Self.helloSHA256)  plain.txt

        """
        let manifest = try ChecksumManifest.parse(text)
        #expect(manifest.entries.count == 1)
        #expect(manifest.unrecognizedLines.isEmpty)
    }

    @Test("a leading ./ is normalized away")
    func dotSlash() throws {
        let manifest = try ChecksumManifest.parse("\(Self.helloSHA256)  ./sub/plain.txt")
        #expect(manifest.entries.first?.name == "sub/plain.txt")
    }

    @Test("an uppercase digest is normalized to lowercase")
    func uppercaseDigest() throws {
        let manifest = try ChecksumManifest.parse("\(Self.helloSHA256.uppercased())  plain.txt")
        #expect(manifest.entries.first?.digest == Self.helloSHA256)
    }

    @Test("a file listing the same name twice keeps both entries")
    func duplicates() throws {
        let text = "\(Self.helloSHA256)  a.txt\n\(Self.helloSHA256)  a.txt\n"
        let manifest = try ChecksumManifest.parse(text)
        #expect(manifest.entries.count == 2)
    }

    // MARK: - Refusals

    @Test("a mixed-algorithm file is refused, naming both algorithms")
    func mixedAlgorithms() {
        let text = "\(Self.helloSHA256)  a.txt\n\(Self.helloMD5)  b.txt\n"
        #expect(throws: ChecksumError.manifestMixesAlgorithms(first: .sha256, second: .md5)) {
            try ChecksumManifest.parse(text)
        }
    }

    @Test("a file with no checksum lines is refused")
    func unreadable() {
        #expect(throws: ChecksumError.manifestUnreadable) {
            try ChecksumManifest.parse("this is just some prose\nand a second line\n")
        }
        #expect(throws: ChecksumError.manifestUnreadable) {
            try ChecksumManifest.parse("")
        }
    }

    /// A tolerant parser that silently drops a line turns "never checked" into "passed", so the
    /// lines it did not understand are reported by number.
    @Test("unrecognized lines are reported, not swallowed")
    func unrecognizedLinesReported() throws {
        let text = """
        \(Self.helloSHA256)  a.txt
        not a checksum at all
        \(Self.helloSHA256)  b.txt
        deadbeefdeadbeef  truncated.txt
        """
        let manifest = try ChecksumManifest.parse(text)
        #expect(manifest.entries.count == 2)
        #expect(manifest.unrecognizedLines == [2, 4])
    }
}
