import Foundation
import Testing

@testable import DirnexCore

/// Parsing the JSON pointer Drive for Desktop leaves in place of a Google-native document, and
/// building the editor URL from it (PLAN.md §M10 Phase 1 "Open `.gdoc` / `.gsheet` / `.gslides`
/// stubs").
@Suite("GoogleDocStub")
struct GoogleDocStubTests {
    /// The real bytes of a `.gdoc`, copied verbatim from the mount on 2026-07-21. The warning
    /// under the empty-string key and the empty `resource_key` are both exactly as Drive writes
    /// them — this is the fixture every "does it parse" test rests on, so it stays real.
    static let realStub = Data(
        (#"{"":"WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!","# +
            #""doc_id":"1615lVvAbc155u1pKSdUhG66Slwbvam1y7ZunPAUffyI","# +
            #""resource_key":"","email":"someone@gmail.com"}"#).utf8
    )

    // MARK: - Recognising a stub by its name

    @Test("each Drive suffix maps to its editor")
    func kindsComeFromTheExtension() {
        #expect(GoogleDocKind(fileNamed: "Notes.gdoc") == .document)
        #expect(GoogleDocKind(fileNamed: "Income.gsheet") == .spreadsheet)
        #expect(GoogleDocKind(fileNamed: "Deck.gslides") == .presentation)
        #expect(GoogleDocKind(fileNamed: "Sketch.gdraw") == .drawing)
        #expect(GoogleDocKind(fileNamed: "Survey.gform") == .form)
    }

    @Test("an ordinary file is not a stub")
    func nonStubExtensionsAreRejected() {
        #expect(GoogleDocKind(fileNamed: "report.pdf") == nil)
        #expect(GoogleDocKind(fileNamed: "notes.txt") == nil)
        #expect(GoogleDocKind(fileNamed: "gdoc") == nil) // no extension at all
        #expect(GoogleDocKind(fileNamed: "Map.gmap") == nil) // a real Drive suffix, different host
    }

    @Test("a name Drive wrote in another case still matches")
    func extensionMatchIsCaseInsensitive() {
        #expect(GoogleDocKind(fileNamed: "Notes.GDOC") == .document)
        #expect(GoogleDocKind(fileNamed: "Income.GSheet") == .spreadsheet)
    }

    @Test("a doubled extension is read from the last component")
    func trailingExtensionWins() {
        // Real file on the mount: `FOP Info.txt.gdoc` — a text file that was converted to a Doc
        // and kept its old suffix in the middle of the name.
        #expect(GoogleDocKind(fileNamed: "FOP Info.txt.gdoc") == .document)
        #expect(GoogleDocKind(fileNamed: "notes.gdoc.txt") == nil)
    }

    // MARK: - Parsing the real payload

    @Test("the real stub parses into its identifier and account")
    func realStubParses() throws {
        let stub = try #require(GoogleDocStub.parse(Self.realStub, fileNamed: "test.gdoc"))
        #expect(stub.kind == .document)
        #expect(stub.documentID == "1615lVvAbc155u1pKSdUhG66Slwbvam1y7ZunPAUffyI")
        #expect(stub.accountEmail == "someone@gmail.com")
        // Written as `""` by Drive, which is not a resource key — it must not reach the URL.
        #expect(stub.resourceKey == nil)
    }

    @Test("the same payload under a .gsheet name opens the spreadsheet editor")
    func kindComesFromTheNameNotThePayload() throws {
        // The stub's JSON is identical across kinds, so the extension is the only signal.
        let stub = try #require(GoogleDocStub.parse(Self.realStub, fileNamed: "Income.gsheet"))
        #expect(stub.kind == .spreadsheet)
        #expect(stub.url.absoluteString.hasPrefix("https://docs.google.com/spreadsheets/d/"))
    }

    @Test("a stub whose name is not a Google suffix is not parsed")
    func payloadAloneIsNotEnough() {
        #expect(GoogleDocStub.parse(Self.realStub, fileNamed: "test.txt") == nil)
    }

    // MARK: - The URL

    @Test("the URL is built from the identifier and the kind")
    func urlShape() {
        let stub = GoogleDocStub(kind: .document, documentID: "abc123")
        #expect(stub.url.absoluteString == "https://docs.google.com/document/d/abc123/edit")
    }

    @Test("every kind lands on the segment Google actually uses")
    func urlSegmentsPerKind() {
        let urls = GoogleDocKind.allCases.map {
            GoogleDocStub(kind: $0, documentID: "abc123").url.absoluteString
        }
        #expect(urls == [
            "https://docs.google.com/document/d/abc123/edit",
            "https://docs.google.com/spreadsheets/d/abc123/edit",
            "https://docs.google.com/presentation/d/abc123/edit",
            "https://docs.google.com/drawings/d/abc123/edit",
            "https://docs.google.com/forms/d/abc123/edit"
        ])
    }

    @Test("the account rides along so a two-account Mac opens the right session")
    func accountBecomesAuthuser() throws {
        let stub = try #require(GoogleDocStub.parse(Self.realStub, fileNamed: "test.gdoc"))
        #expect(stub.url.absoluteString.hasSuffix("/edit?authuser=someone@gmail.com"))
    }

    @Test("a resource key is carried into the query")
    func resourceKeyBecomesAQueryItem() {
        let stub = GoogleDocStub(kind: .document, documentID: "abc123", resourceKey: "0-aBcD_e")
        #expect(
            stub.url.absoluteString == "https://docs.google.com/document/d/abc123/edit?resourcekey=0-aBcD_e"
        )
    }

    // MARK: - Refusing what should fall back to a plain open

    @Test("a file that merely ends in .gdoc is not a stub")
    func nonJSONIsRejected() {
        #expect(GoogleDocStub.parse(Data("not json at all".utf8), fileNamed: "x.gdoc") == nil)
        #expect(GoogleDocStub.parse(Data(), fileNamed: "x.gdoc") == nil)
    }

    @Test("JSON without a usable doc_id is rejected")
    func missingIdentifierIsRejected() {
        let noID = Data(#"{"email":"someone@gmail.com"}"#.utf8)
        let emptyID = Data(#"{"doc_id":"","email":"someone@gmail.com"}"#.utf8)
        #expect(GoogleDocStub.parse(noID, fileNamed: "x.gdoc") == nil)
        #expect(GoogleDocStub.parse(emptyID, fileNamed: "x.gdoc") == nil)
    }

    @Test("an identifier that could steer the URL elsewhere is refused")
    func hostileIdentifiersAreRefused() {
        // The value comes out of a file's *contents* and ends up in a URL the app opens, so the
        // charset guard is a security boundary, not tidiness. Each of these would otherwise
        // escape the intended path or host.
        for hostile in ["../../evil", "abc/../..", "abc?x=1", "abc#frag", "a b", "évil"] {
            let data = Data(#"{"doc_id":"\#(hostile)"}"#.utf8)
            #expect(
                GoogleDocStub.parse(data, fileNamed: "x.gdoc") == nil,
                "\(hostile) must not produce a URL"
            )
        }
    }

    @Test("a resource key that fails the same guard is dropped, not fatal")
    func hostileResourceKeyIsDroppedNotFatal() throws {
        let data = Data(#"{"doc_id":"abc123","resource_key":"../x"}"#.utf8)
        let stub = try #require(GoogleDocStub.parse(data, fileNamed: "x.gdoc"))
        #expect(stub.resourceKey == nil)
        #expect(stub.url.absoluteString == "https://docs.google.com/document/d/abc123/edit")
    }

    @Test("something far too large to be a stub is refused before it is decoded")
    func oversizedFileIsRefused() {
        // A real stub is ~180 bytes. A `.gdoc`-named file of any size is refused on its size, so
        // a big file never gets read into a JSON decoder.
        let padding = String(repeating: " ", count: 70 * 1024)
        let data = Data((#"{"doc_id":"abc123"}"# + padding).utf8)
        #expect(GoogleDocStub.parse(data, fileNamed: "x.gdoc") == nil)
    }
}
