import Foundation
import Testing

@testable import DirnexCore

/// One case from `Fixtures/license-vectors.json`, the file both repos check (PLAN.md §M29 Slice 1).
struct LicenseVector: Decodable, Sendable, CustomTestStringConvertible {
    struct Expected: Decodable, Sendable {
        let id: String
        let to: String
        let issued: String
        let until: String
        let key: String
    }

    let name: String
    let note: String
    let input: String
    /// `valid`, or a ``LicenseKeyError`` raw value.
    let expect: String
    let license: Expected?

    var testDescription: String {
        "\(name) → \(expect)"
    }

    /// Whether `result` is what this vector expects, fields included.
    func isMatched(by result: Result<LicenseKey, LicenseKeyError>) -> Bool {
        switch result {
        case let .failure(error):
            return error.rawValue == expect
        case let .success(key):
            guard expect == "valid", let license else { return false }
            return key.text == license.key && key.id == license.id && key.licensee == license.to
                && key.issued.description == license.issued
                && key.until.description == license.until
        }
    }
}

struct LicenseVectorFile: Decodable, Sendable {
    let publicKey: String
    let vectors: [LicenseVector]

    /// The fixture, or `nil` when it's missing. A missing file must fail ``fixtureIsComplete``
    /// rather than leave the parameterized test with nothing to run, which would pass.
    static let shared: LicenseVectorFile? = {
        guard let url = Bundle.module.url(
            forResource: "license-vectors",
            withExtension: "json",
            subdirectory: "Fixtures"
        ),
            let data = try? Data(contentsOf: url)
        else {
            return nil
        }
        return try? JSONDecoder().decode(LicenseVectorFile.self, from: data)
    }()
}

/// The shared test vectors, generated by the signer in the private repo (`tools/license`) with a
/// throwaway test key and copied here unchanged. The signer's own tests check the same file, so the
/// store's server and the app agree on every valid key and every refusal.
@Suite("License key vectors")
struct LicenseKeyVectorTests {
    private func verifier() throws -> LicenseVerifier {
        try LicenseVerifier(publicKey: #require(LicenseVectorFile.shared).publicKey)
    }

    @Test("the fixture is there, and every outcome has a vector")
    func fixtureIsComplete() throws {
        let file = try #require(LicenseVectorFile.shared)
        #expect(file.vectors.count >= 27)
        let outcomes = Set(file.vectors.map(\.expect))
        #expect(outcomes == Set(["valid"] + LicenseKeyError.allCases.map(\.rawValue)))
    }

    @Test("each vector", arguments: LicenseVectorFile.shared?.vectors ?? [])
    func vector(_ vector: LicenseVector) throws {
        let result = try verifier().check(vector.input)
        #expect(vector.isMatched(by: result), "\(vector.note) Got \(result).")
    }

    @Test(
        "negative control: a verifier that skips the signature fails exactly the signature vectors"
    )
    func skippingTheSignatureIsCaught() throws {
        let vectors = try #require(LicenseVectorFile.shared).vectors
        let skipping = LicenseVerifier { _, _ in true }
        let misjudged = vectors.filter { !$0.isMatched(by: skipping.check($0.input)) }.map(\.name)
        let signatureVectors = vectors.filter { $0.expect == "badSignature" }.map(\.name)
        #expect(misjudged == signatureVectors)
        #expect(signatureVectors.count >= 4)
    }

    @Test("negative control: Foundation's base64 decoder would accept the non-canonical signature")
    func foundationBase64IsLenient() throws {
        let vectors = try #require(LicenseVectorFile.shared).vectors
        let loose = try #require(vectors.first { $0.name == "non-canonical-trailing-bits" })
        let valid = try #require(vectors.first { $0.name == "valid" })
        let looseSignature = String(try #require(loose.input.split(separator: ".").last))
        let validSignature = String(try #require(valid.input.split(separator: ".").last))

        // Foundation reads both spellings as the same 64 bytes, so a decoder built on it would
        // accept the vector the signer refuses.
        #expect(foundationDecode(looseSignature) == foundationDecode(validSignature))
        #expect(foundationDecode(looseSignature) != nil)
        #expect(Base64URL.decode(looseSignature) == nil)
    }

    @Test("every one-character change to a valid key is refused")
    func everyMutationIsRefused() throws {
        let verifier = try verifier()
        let vectors = try #require(LicenseVectorFile.shared).vectors
        let key = try #require(vectors.first { $0.name == "valid" }).input
        let characters = Array(key)
        for index in characters.indices {
            for replacement: Character in ["A", "z", "0", "-", "_", "."] where characters[index] != replacement {
                var changed = characters
                changed[index] = replacement
                let result = verifier.check(String(changed))
                #expect(throws: LicenseKeyError.self, "position \(index) → \(replacement)") {
                    try result.get()
                }
            }
        }
    }

    private func foundationDecode(_ base64URL: String) -> Data? {
        var text = base64URL.replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        text += String(repeating: "=", count: (4 - text.count % 4) % 4)
        return Data(base64Encoded: text)
    }
}
