import Foundation

/// Which Google editor a Drive stub file belongs to (PLAN.md §M10 Phase 1 "Open `.gdoc` /
/// `.gsheet` / `.gslides` stubs").
///
/// A Google-native document has no bytes to download — Drive for Desktop writes a ~180-byte JSON
/// pointer in its place — so the *extension* is the only thing that says which editor owns it. The
/// stub's own JSON does not: the payload is identical across kinds.
public enum GoogleDocKind: String, Sendable, CaseIterable {
    case document
    case spreadsheet
    case presentation
    case drawing
    case form

    /// The suffix Drive for Desktop writes for this kind, without the dot.
    public var fileExtension: String {
        switch self {
        case .document: "gdoc"
        case .spreadsheet: "gsheet"
        case .presentation: "gslides"
        case .drawing: "gdraw"
        case .form: "gform"
        }
    }

    /// The first path segment of the editor's URL on `docs.google.com`.
    ///
    /// The singular/plural mix is Google's, not a typo: `document` and `presentation` are singular
    /// while `spreadsheets`, `drawings` and `forms` are plural. Deriving it from the case name
    /// would therefore be wrong for three of the five.
    var urlSegment: String {
        switch self {
        case .document: "document"
        case .spreadsheet: "spreadsheets"
        case .presentation: "presentation"
        case .drawing: "drawings"
        case .form: "forms"
        }
    }

    /// The kind a file name announces, or `nil` for anything that is not a Google stub.
    ///
    /// Matched case-insensitively on the suffix alone, the way `ArchiveType.isBrowsable` matches
    /// archives: a stub is recognised by its name before anything reads it, so an ordinary file
    /// never pays for this feature.
    ///
    /// Deliberately covers only the five kinds that live under `docs.google.com/<segment>/d/<id>`.
    /// Drive writes a handful of others (`.gmap`, `.gscript`, `.gsite`, `.gjam`) whose URLs are on
    /// different hosts with different shapes — an unrecognised suffix falls back to the ordinary
    /// open, which is a working outcome, while a *guessed* URL is a broken one.
    public init?(fileNamed name: String) {
        let suffix = (name as NSString).pathExtension.lowercased()
        guard !suffix.isEmpty,
              let kind = GoogleDocKind.allCases.first(where: { $0.fileExtension == suffix })
        else { return nil }
        self = kind
    }
}

/// A parsed Google Drive stub file — the pointer that stands in for a Google-native document on
/// the Desktop mount, and the `docs.google.com` URL it resolves to.
///
/// **The stub does not contain a URL.** Probed 2026-07-21 against real files on the mount; the
/// whole payload is
/// `{"":"WARNING! DO NOT EDIT THIS FILE! …","doc_id":"1615lVv…","resource_key":"","email":"…"}` —
/// note that the warning sits under an *empty-string* key, and that there is no `url` field
/// anywhere, contrary to what this repo's own plan said before the probe. The link therefore has
/// to be **constructed** from `doc_id` plus the kind the extension implies.
public struct GoogleDocStub: Sendable, Hashable {
    /// Which editor opens it — from the file's extension, not from its contents.
    public let kind: GoogleDocKind
    /// Drive's identifier for the document, the `doc_id` field.
    public let documentID: String
    /// The resource key a legacy link-shared file needs to be reachable by link, or `nil` when the
    /// stub carries none. Empty in every file probed here — Google issues these only for items
    /// shared before the 2021 security update — but it is written into every stub, so it is
    /// carried through rather than dropped.
    public let resourceKey: String?
    /// Which signed-in Google account the file belongs to, the `email` field.
    public let accountEmail: String?

    public init(
        kind: GoogleDocKind,
        documentID: String,
        resourceKey: String? = nil,
        accountEmail: String? = nil
    ) {
        self.kind = kind
        self.documentID = documentID
        self.resourceKey = resourceKey
        self.accountEmail = accountEmail
    }

    /// Where to send the browser: `https://docs.google.com/<segment>/d/<id>/edit`.
    ///
    /// `authuser` is the reason the account email is parsed at all. Drive for Desktop happily
    /// mounts two accounts at once, and a plain document link resolves against whichever Google
    /// session the browser happens to have first — so opening a second-account document lands on
    /// "You need access" for a file the user owns. Naming the account routes it to the right
    /// session, and degrades to Google's account chooser when that account isn't signed in, which
    /// is a recoverable place to be.
    public var url: URL {
        var components = URLComponents()
        components.scheme = "https"
        components.host = "docs.google.com"
        components.path = "/\(kind.urlSegment)/d/\(documentID)/edit"
        var query: [URLQueryItem] = []
        if let resourceKey {
            query.append(URLQueryItem(name: "resourcekey", value: resourceKey))
        }
        if let accountEmail {
            query.append(URLQueryItem(name: "authuser", value: accountEmail))
        }
        components.queryItems = query.isEmpty ? nil : query
        // Every component is built from characters `validated(_:)` already restricted to the
        // unreserved set (plus an email that `URLComponents` percent-encodes), so this cannot fail.
        return components.url ?? URL(string: "https://docs.google.com")!
    }

    /// Parse the bytes of the file named `name`, or `nil` when they are not a stub of a kind we
    /// can open.
    ///
    /// Returning `nil` rather than throwing is the point: every caller has a working fallback —
    /// hand the file to its default application, exactly as before — so a `.gdoc` that turns out
    /// to hold something else opens as a file instead of raising an error about a Google document
    /// the user never asked about.
    public static func parse(_ data: Data, fileNamed name: String) -> GoogleDocStub? {
        guard let kind = GoogleDocKind(fileNamed: name),
              data.count <= maximumSize,
              let payload = try? JSONDecoder().decode(Payload.self, from: data),
              let documentID = validated(payload.documentID)
        else { return nil }
        return GoogleDocStub(
            kind: kind,
            documentID: documentID,
            resourceKey: validated(payload.resourceKey),
            accountEmail: payload.email.flatMap { $0.isEmpty ? nil : $0 }
        )
    }

    /// A ceiling on what will even be considered a stub. The real ones are ~180 bytes; this exists
    /// so a large file that merely ends in `.gdoc` is rejected on its size instead of being read
    /// into memory and handed to a JSON decoder.
    private static let maximumSize = 64 * 1024

    /// The characters a Drive identifier is made of. Anything else is refused.
    ///
    /// This is a guard, not a formatting nicety: the value comes out of a *file's contents* and
    /// goes into a URL the app then opens, so an unconstrained `doc_id` would let a hostile file
    /// choose the destination (`../../…`, a host of its own, a `javascript:` payload). Real
    /// identifiers and resource keys are alphanumerics with `-` and `_`.
    private static let identifierCharacters = CharacterSet(
        charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
    )

    private static func validated(_ identifier: String?) -> String? {
        guard let identifier, !identifier.isEmpty,
              identifier.unicodeScalars.allSatisfy(identifierCharacters.contains)
        else { return nil }
        return identifier
    }
}

/// The stub's JSON. The warning string's key is the empty string, which no property here maps to —
/// it is a message for whoever opens the file in an editor, and is ignored.
///
/// A file-scope type rather than a nested one only because `CodingKeys` would then be a third level
/// of nesting, which SwiftLint refuses.
private struct Payload: Decodable {
    let documentID: String?
    let resourceKey: String?
    let email: String?

    enum CodingKeys: String, CodingKey {
        case documentID = "doc_id"
        case resourceKey = "resource_key"
        case email
    }
}
