import AppKit
import DirnexCore

/// Opens a Google-native document from the Drive for Desktop mount in the browser (PLAN.md §M10
/// Phase 1), the app-side half of `DirnexCore.GoogleDocStub`.
///
/// A `.gdoc` / `.gsheet` / `.gslides` on the mount is not a document — it is a ~180-byte JSON
/// pointer at one that lives on Google's servers. Handing it to `NSWorkspace` the way any other
/// file is handed over therefore "works": it opens a text editor showing
/// "WARNING! DO NOT EDIT THIS FILE!", which is the one thing the user did not ask for. This is the
/// same hand-off shape M4 uses for external tools — the core decides *where*, the app performs the
/// launch.
enum GoogleDocLauncher {
    /// Open `entry` in the browser if it is a Google document stub, reporting whether it was one.
    ///
    /// `false` means "not mine, open it normally", and it is deliberately the answer for a
    /// `.gdoc`-named file whose bytes are not a stub — that is a real file the user should get to
    /// see. Once the bytes *do* parse, the answer is `true` whatever the browser does with the
    /// URL, because falling back to a text editor at that point would show the warning banner
    /// instead of a document we know exists.
    ///
    /// Reads with `.mappedIfSafe` so a large file that merely ends in `.gdoc` is measured rather
    /// than loaded — `GoogleDocStub.parse` refuses it on its size.
    @discardableResult
    static func open(_ entry: FileEntry) -> Bool {
        guard entry.path.backend == .local, GoogleDocKind(fileNamed: entry.name) != nil,
              let data = try? Data(contentsOf: entry.path.localURL, options: [.mappedIfSafe]),
              let stub = GoogleDocStub.parse(data, fileNamed: entry.name)
        else { return false }
        NSWorkspace.shared.open(stub.url)
        return true
    }
}
